import { Palette, Button } from "std-widgets.slint";
import {
    Backups,
    MinecraftSaveMeta,
    MinecraftSaveVersionMeta,
} from "../logic/backups.slint";
export component Card inherits Rectangle {
    border-radius: 12px;
    preferred-width: 400px;
    preferred-height: 100px;
    background: Palette.alternate-background;
    @children
}

export component SaveCard inherits Card {
    in property <MinecraftSaveMeta> item;
    callback show-detailed-information([MinecraftSaveVersionMeta]);
    VerticalLayout {
        padding: 8px;
        spacing: 4px;
        Text {
            text: item.name;
            font-size: 24px;
        }

        Text {
            // text: item.description; //TODO
        }

        HorizontalLayout {
            spacing: 4px;
            alignment: end;
            Button {
                icon: @image-url("../icon/backup.png");
                colorize-icon: true;
                clicked => {
                    Backups.run-backup(item.id, item.name, 255);
                }
            }

            Button {
                text: "详细信息(正在开发)";
                clicked => {
                    show-detailed-information(item.versions)
                }
            }
        }
    }
}
