import { Switch } from "std-widgets.slint";
export component WithLabel inherits HorizontalLayout {
    in property <string> text;

    alignment: start;
    spacing: 8px;

    Text {
        text: text;
        min-width: 120px;
        max-width: 120px;
    }

    @children
}

export component SwitchWithLabel inherits WithLabel {
    in-out property <bool> checked;
    callback toggled();
    Switch {
        checked <=> checked;
        toggled => toggled();
    }
}
