export struct MinecraftSaveVersionMeta {     
    type: int,
    description: string,
}


export struct MinecraftSaveMeta {
  id: string,
  name: string,
  versions: [MinecraftSaveVersionMeta],
}

export global Backups {
    in-out property <[MinecraftSaveMeta]> backups;
    callback run-backup(id: string, name: string, type: int);
    callback change-description(name: string, description: string);
    callback add-scan-root(path: string);
    callback refresh();
}
